#ifndef COMPUTREECORE_GLOBAL_H
#define COMPUTREECORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPUTREECORE_LIBRARY)
#  define COMPUTREECORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPUTREECORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPUTREECORE_GLOBAL_H
