#ifndef CT_READER_TERRASCANPRJ_DEF_MODELS_H
#define CT_READER_TERRASCANPRJ_DEF_MODELS_H

/**
  * DEFINITION OF MODELS USED BY THE TERRASCANPRJ READER
  */

#define DEF_CT_Reader_TERRASCANPRJ_boxOut    "box"
#define DEF_CT_Reader_TERRASCANPRJ_grpOut    "grp"
#define DEF_CT_Reader_TERRASCANPRJ_headerOut    "header"

#endif // CT_READER_TERRASCANPRJ_DEF_MODELS_H
